name: Generate Snake Animation

on:
  schedule: # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Snake
        uses: Platane/snk@v3.3.0
        with:
          github_user_name: Arvss07
          outputs: |
            dist/snake.svg
            dist/snake.gif

      - name: Push Snake to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
          publish_branch: output